name: Update Submodules

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # lets you manually trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        submodules: false  # we will update manually

    - name: Pull latest submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge --recursive

    - name: Commit updated submodules (optional)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Update submodules to latest commit" || echo "No changes"
        git push || echo "No push needed"
